remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /Project1_BaltMap/project1.html
  Project 2: /Project2_BaltMap/project2.html
  Project 3: /Project3_Final_project/project3.html
  Project 4: /Project4/project4.html
